mv build/linux/x64/release/bundle/csv_generator build/linux/x64/release/bundle/lib/csv_generator
cp linux/*.desktop build/linux/x64/release/bundle/
cp linux/csv_generator.*.sh build/linux/x64/release/bundle/
cp linux/install-*.sh build/linux/x64/release/bundle/
cp linux/csv_generator build/linux/x64/release/bundle/
cp README.md build/linux/x64/release/bundle/
cp linux/csv_generator.png build/linux/x64/release/bundle/
cp linux/libCwtch.so build/linux/x64/release/bundle/lib/
cp linux/tor build/linux/x64/release/bundle/lib
